<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default Suite" duration-ms="20495" started-at="2019-11-14T19:54:49 UZT" finished-at="2019-11-14T19:55:09 UZT">
    <groups>
      <group name="functional">
        <method signature="LoginTests.Login_with_invalid_userid()[pri:0, instance:com.Automationpractice.login.LoginTests@3abbfa04]" name="Login_with_invalid_userid" class="com.Automationpractice.login.LoginTests"/>
      </group> <!-- functional -->
    </groups>
    <test name="automationpractice" duration-ms="20495" started-at="2019-11-14T19:54:49 UZT" finished-at="2019-11-14T19:55:09 UZT">
      <class name="com.Automationpractice.login.LoginTests">
        <test-method status="PASS" signature="initializeReporter()[pri:0, instance:com.Automationpractice.login.LoginTests@3abbfa04]" name="initializeReporter" is-config="true" duration-ms="74" started-at="2019-11-14T19:54:49 UZT" finished-at="2019-11-14T19:54:49 UZT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeReporter -->
        <test-method status="PASS" signature="init()[pri:0, instance:com.Automationpractice.login.LoginTests@3abbfa04]" name="init" is-config="true" duration-ms="11677" started-at="2019-11-14T19:54:49 UZT" finished-at="2019-11-14T19:55:00 UZT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="Login_with_invalid_userid()[pri:0, instance:com.Automationpractice.login.LoginTests@3abbfa04]" name="Login_with_invalid_userid" duration-ms="7995" started-at="2019-11-14T19:55:00 UZT" finished-at="2019-11-14T19:55:08 UZT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login_with_invalid_userid -->
        <test-method status="FAIL" signature="saveReport()[pri:0, instance:com.Automationpractice.login.LoginTests@3abbfa04]" name="saveReport" is-config="true" duration-ms="2" started-at="2019-11-14T19:55:08 UZT" finished-at="2019-11-14T19:55:08 UZT">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at Utils.Reporter.saveReport(Reporter.java:49)
at Driver_Factory.NonStaticDriver.saveReport(NonStaticDriver.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:683)
at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:658)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:642)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- saveReport -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.Automationpractice.login.LoginTests@3abbfa04]" name="closeBrowser" is-config="true" duration-ms="777" started-at="2019-11-14T19:55:08 UZT" finished-at="2019-11-14T19:55:09 UZT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.Automationpractice.login.LoginTests -->
    </test> <!-- automationpractice -->
  </suite> <!-- Default Suite -->
</testng-results>
